- build.gradle.kts
- gradle/libs.versions.toml
Kompendium ser ut til å inkludere det nødvendige for å få generert og vist swagger UIet så kan derfor inntil videre fjerne både ktor-openapi og ktor-swagger som for meg ser ubrukt ut. Dette gjør også at vi får fjernet en sårbarhet.
> Fjern ubrukte dependencies openapi og swagger siden dette inkluderes via kompendium i stedet

- .github/workflows/build-deploy.yaml
Litt usikker på om man må endre noe i forbindelse med octo-sts greiene. Det er jo fortsatt dette repoet som trenger token, så er bare frågan om man må legge til noe ekstra fra `bygning-github-workflows`. Tenker bare få inn denne og se om det funker
> Switch github workflow master

- src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/EgenregisteringRoutes.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringsService.kt
Unngår den litt snåle instansieringen samt henter ikke bygning fra matrikkel to ganger
Kan hende det gir mer mening å sende bygningClient videre til EgenregService i stedet for å gjøre det ute i routen, litt usikker på fordeler/ulemper rundt det.
> Remove bygningclient from egenreg service

- build.gradle.kts
- src/intTest/kotlin/no/kartverket/matrikkel/bygning/TestWithDb.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/config/Env.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/config/LoadConfiguration.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/MatrikkelApiConfig.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/MatrikkelBygningClient.kt
- src/main/resources/application-local.conf
- src/main/resources/application.conf
* Etabler et env-konsept for å skille mellom config når man kjører lokalt og på SKIP. Litt usikker på det beste her, og om det f.eks. finnes andre variabler man kan bruke for å skille hvor man kjører.
* Skill ut config i to separate filer for å unngå å ha default-verdier og lokale verdier i prod-config.
* Hovedtanken er nå at i "prod" modus så vil app-en feile hvis nødvendige config-verdier ikke er satt i stedet for å bruke default-verdier
Vi bør jo fortsatt ha mulighet til å gå direkte mot matrikkel APIet når vi kjører lokalt tenker jeg, så ikke sikkert det blir helt riktig å ha `Env.isLocal()` som betingelse for hvor vi kjører, men det får vi bare justere når vi jobber med dette fremover.
> TH-51 Justeringer av oppsett lokalt

- src/main/kotlin/no/kartverket/matrikkel/bygning/models/requests/EgenregistreringRequest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringsService.kt
Ref. @christianmosveen som nevnte at man _måtte_ sende inn bruksenhetID når man kun registrerer på bygning
> Tillat bruksenhetregistrering å være nullable

- .gitignore
- Dockerfile
- README.md
- docker-compose.yaml
- src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
- src/main/resources/application-local.conf
CC @christianmosveen 
Tillater nå at `PORT` og `INTERNAL_PORT` kan leses automatisk fra en `.env` fil.
Valgte å ikke sette dette i application config da man ikke har `loadConfiguration` tilgjengelig ved oppstart av server.
Kan jo være det er verdt å se på å legge inn støtte for `.env` generelt når man først støtter det på et vis her, men det kan komme senere, methinks
Flytta også litt på README så det var lettere å se hvor lite som skulle til for å faktisk sette opp alt
> Legg opp til enklere portkonflikthåndtering i docker og applikasjon

- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/EgenregistreringRouteTest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/requests/EgenregistreringRequest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/BygningRoutes.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/EgenregisteringRoutes.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringService.kt
Var litt snålt å ha f. eks ha `bruksareal.bruksareal = 125.0` fremfor å tydeliggjøre at man har en bruksareal<i>registrering</i> som har bruksareal
> Sett feltnavn for registreringer til å inneholde registrering

- build.gradle.kts
- gradle/libs.versions.toml
- src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/serializers/InstantSerializer.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/serializers/LocalDateSerializer.kt
Test på å se hva som skal til for å erstatte kotlinx.time med java.time
Ser primært ut som at to ting må gjøres:
* Skrive egne serialiserer for Instant og LocalDate og legge disse på de aktuelle feltene (man får en kompileringsfeil hvis man angir java.time.LocalDate uten å ha korrekt serialiserer)
* Konfigurere kompendium slik at den forstår hvordan java.time typene skal håndteres i OpenAPI spesifikasjonen. Benytter da typene som finnes i henhold til OpenAPI spec-en (date og date-time): https://swagger.io/docs/specification/data-models/data-types/
Ta gjerne en titt så kan vi ta en vurdering på hva vi ønsker å gå videre med.
> Erstatt kotlinx.time med java.time

- .github/actions/setup-java/action.yaml
- .github/workflows/build-deploy.yaml
- .github/workflows/codeql.yaml
- .github/workflows/dependency-review-pr.yaml
- .github/workflows/dependency-submission.yaml
* Legger til 2 workflows: En som submitter alle dependencies til submission APIet på main-branchen og en som sjekker etter nye dependencies med sårbarheter eller uønskede lisenser på PR-er
* Sjekker også etter sårbarheter i tillegg til lisenser i 3. parts libs
* Tillater følgende lisenser: MIT og Apache 2
> Tb 52 Legg til action dependency review

- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/EgenregistreringRepositoryTest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Bygning.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/BygningExtensions.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Egenregistrering.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/repositories/EgenregistreringRepository.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/dto/request/EgenregistreringRequest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/BygningService.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringService.kt
- src/main/resources/db/migration/V1__init_db.sql
- src/test/kotlin/no/kartverket/matrikkel/bygning/models/BygningExtensionsTest.kt
* Endrer litt på strukturen for databaselagringen for å rydde opp i domeneobjektet `Egenregistrering`
* Sender EgenregService inn til BygningService fremfor EgenregRepo
* Lager funksjoner for å aggregere en liste med egenregistreringer til å fylle sist registrerte felt for bruksenhet og bygning
Jeg er ikke helt sikker på om bruksenhetaggregeringen trenger å være så "smart" som den er med filtrering og å sette opp et pair, sånn som jeg har kommentert.
NB: Hvis man nå registrerer på liste-registreringene (Oppvarming og Energikilder), så vil _hele_ registreringen få nytt registreringstidspunkt, det går ikke individuelt per felt
> TB-59 Aggregerte registeringer på bruksenhet og bygning

- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Bygning.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/BygningExtensions.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Egenregistrering.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/HTTP.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/dto/response/BygningResponse.kt
Ved å sende inn null til APIet på verdien til feltet så registrerer du en "sletting". Det vil si at f. eks ved innsending av:
`bruksarealRegistrering.bruksareal = null` så vil du få svar `bruksareal.egenregistrert.bruksareal = null`, men med registreringstidspunktet til null verdien. Det er altså forskjell på en spesifikt registrert null og en verdi som aldri har vært der. Om det er dette som skal bety sletting i fremtiden spørs nok, men det er hvert fall en start for egenregistrering å kunne slette tidligere innsendte verdier.
NB: Dette er ikke løst for liste-registreringer, her må vi gjøre noe glupere.
> TB-66 Fjerne tidligere registrert felt

- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/TestApplicationWithDb.kt
- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/EgenregistreringRouteTest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/dto/response/BygningResponse.kt
Gjør at man slipper at responsobjektene for multikilder blir `{}`
> Gjør Multikilderesponse nullable

- matrikkel-api/src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/EnumIds.kt
- matrikkel-api/src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/XmlDate.kt
- matrikkel-api/src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/id/EnumIds.kt
- matrikkel-api/src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/id/Ids.kt
- matrikkel-api/src/testFixtures/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/builders/BruksenhetBuilder.kt
- matrikkel-api/src/testFixtures/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/builders/BygningBuilder.kt
- matrikkel-api/src/testFixtures/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/builders/BygningsstatusHistorikkBuilder.kt
- matrikkel-api/src/testFixtures/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/builders/DatoBuilders.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/ByggeaarDeriver.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/MatrikkelBygningClient.kt
- src/test/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/ByggeaarDeriverTest.kt
- src/test/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/MatrikkelBygningClientTest.kt
Legger til utledning av byggeår.
Etter diskusjon med Cato kom vi fram til at vi sjekker _registreringsdato_ for å vurdere hvorvidt det skal være mulig å utlede byggeåret, men bruker _statusdato_ for å faktisk utlede byggeåret.
Det vil likevel kunne dukke opp en situasjon, slik som @kvstrant har sendt tidligere, hvor registreringsdato er satt til å være etter godkjent dato, men statusen er satt til å være i år 320 f. eks. I disse tilfellene er det jo åpenbart noe feil, men vi må nok bare gå opp hva som regnes som en akseptabel terskel i forskjell mellom registreringsdato og statusdato.
> TB-67 Legg til utledning av byggeår basert på bygningsstatushistorikk

- matrikkel-api/src/testFixtures/kotlin/no/kartverket/matrikkel/bygning/matrikkelapi/builders/BygningBuilder.kt
- src/test/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/MatrikkelBygningClientTest.kt
Tanken her er at den ene testen sjekker at mappingen ikke forventer at felt som ikke trenger være fylt inn, må være fylt inn, mens den andre testen sjekker at alle feltene som kan mappes, blir mappet. Så blir det andre mer spissede tester for der spesifikke kombinasjoner skal mappes litt spesielt, som f.eks. byggeår. Men hvordan få dette til å fremgå av navnene?
> TH-58: Juster litt på testene

- src/main/kotlin/no/kartverket/matrikkel/bygning/models/RegistreringAktoer.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/StatusPages.kt
Testmiljøer inneholder syntetiske fødselsnummere, ikke faktiske fødselsnummere, så vi må tillate disse.
Feilen dukket opp som en uhåndtert `InternalServerError`, siden det var en del av `IllegalArgumentException`, men ble ikke spesifikt håndtert.
Har lagt inn det som en default, samt også en ytterligere default for `IllegalArgumentException`
Jeg er _ikke_ fan av chainingen her, men det virket å være greieste måte å ha fallbacks til InternalServerError. Må gå opp beste måte å håndtere de exceptionene som kan dukke opp. Mulig vi bare burde senke detaljeringsnivået i StatusPages?
> TB-71 Tillat syntetiske fødselsnummere, og bruk InternalServerError som default StatusPage

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/kodelister/EgenregistreringKoder.kt
Vi har kommet frem til hva slags beskrivelser vi ønsker til hver kildekode. Hadde vært flott å lagre disse hos dere. Om dere vil beholde de originale, kan vi bare lage vår egen mapping
> Endre beskrivelser av kildematerialkoder

- gradle/libs.versions.toml
- web/build.gradle.kts
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/TestApplicationWithDb.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/ekstern/bygning/BygningEksternTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BygningRouteTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/Authentication.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/EksternRoutes.kt
- web/src/main/resources/application-local.conf
- web/src/main/resources/application.conf
Legg til autentisering med maskinporten for eksternt bygning API
* Krever gyldig maskinporten token samt spesifikt scope som er definert i API integrasjonen i maskinporten
* Mulighet til å disable autentisering lokalt (kun mulig å aktivere ved lokal kjøring)
* Bruker mock-oauth2-server fra NAV IKT for integrasjonstester lokalt
> Autentisering mot maskinporten

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/kodelister/EgenregistreringKoder.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregisteringRoutes.kt
* Slettet valideringskode og tilhørende testkode
* En integrasjonstest som sjekket en ugyldig egenregistrering request er skrevet om til å inneholde en ugyldig BRA request i stedet.
> Fjern Plantegninger som gyldig kildemateriale inkludert validering som ikke lenger er nødvendig

- Dockerfile
* I praksis kjører vi ikke som root når vi kjører på SKIP, men dette er uansett ryddig å ha på plass
* Vi må benytte UID 150 fordi Skiperator hardkoder denne brukeren når imaget blir kjørt
> Legg til egen user og user_id i dockerimage

- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/TestApplicationWithDb.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/Authentication.kt
- web/src/main/resources/application.conf
Secret fra digdirator oppretter `MASKINPORTEN_SCOPES`, ikke `MASKINPORTEN_SCOPE`.
Det gir uansett mening ettersom vi kan få flere scopes, ikke bare ett. Disse er i så fall typisk mellomromseparerte.
> Rename scope -> scopes

- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/TestApplicationWithDb.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/config/Env.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/Authentication.kt
- web/src/main/resources/application-local.conf
- web/src/main/resources/application.conf
Fikser en feil som gjorde at `Authentication` plugin ikke ble installert, som førte til at man ikke kunne kjøre applikasjonen med endepunkter som hadde en `authenticate` over seg
> Fiks feil i maskinporten config som gjør at authenticate ikke kan kjøres i endepunkter

- gradle/libs.versions.toml
- web/build.gradle.kts
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
Setter Instant til type string og format date-time.
* Pga av et issue i smiley4 skjema genereringen (som er rapportert) må vi ha en del logikk for å legge på custom prosessering av Instant-typen.
* Resten generering er hentet fra DEFAULT-generatoren og skal dermed oppføre seg likt som før.
TB-101
> Konfigurerer OpenAPI generator til å håndtere Instant-typer korrekt

- .github/workflows/dependency-submission.yaml
Fiks på forrige [PR](https://github.com/kartverket/matrikkel-bygning-egenregistrering/pull/194). Trenger et PAT for å få hentet ut private GitHub Packages i gradle jobbene, også i denne workflowen. Misset den i forrige PR.
Er det noen flere steder dere kan tenke dere at denne må inn? Hvis noen vet om en bedre/mer sentralisert måte enn å legge den til enn i hver eneste workflow så skrik gjerne ut 😄
> TS-130 Legg til PAT som env i dependency-submission workflow

- gradle/libs.versions.toml
- infrastructure/build.gradle.kts
jaxws-rt avhengigheten var definert i modulen matrikkel-api som nå er fjernet. La derfor denne inn igjen i `integration` modulen samme sted som vi trekker wsclient-en. 
Den bør kunne være runtimeOnly da den ikke trengs under bygging/kompilering (og er derfor den først feilet under oppstart av applikasjonen da først er da klassene trengs). 
Gjorde også en liten opprydding i libs.toml og fjernet noen ubrukte definisjoner.
Fint å teste denne i dev-miljøet før vi merger.
> Legg til manglende dependency mot jaxws-rt etter innføring av wsclient

- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
I stedet for å legge på en custom annotasjon som post-prosesseres senere legger vi dynamisk på noen innebygde annotasjoner (Type og Format). Disse blir automatisk prosesser og vi kan dermed fjerne custom prosessering.
Grunnen til at vi trenger å legge på annotasjonene dynamisk er at Instant er en ekstern klasse som vi ikke kan annotere direkte.
> Forenkle custom prosessering av type og format for Instant i OpenAPI dokumentasjon

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/bygning/BygningService.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BruksenhetId.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Bygning.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningId.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/LocalBygningClient.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClient.kt
- infrastructure/src/test/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClientTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/bygning/BygningEksternResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningResponse.kt
* Endringen en at vi bruker primitive typer som egentlig kan være en egen type.  Typisk vil typene bli brukt i domene/applikasjonslaget, mens man i Request/Response-objektene vil bevare primitive typer for serialisering/deserialisering. Dette omhandler BruksenhetId.kt og BygningId.kt
* TB-135
> Gjør om BruksenhetId & BygningId til ValueObjects

- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/MatrikkelApi.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/HTTP.kt
- web/src/main/resources/logback-cloud.xml
- web/src/main/resources/logback.xml
* call_id endres til request_id som gjør det enkelt å f.eks. hente alle logger med en gitt request_id.
* sender med request_id med headere x-request-id slik at vi også kan få inkludert loggene til matrikkelen når vi gjør kall mot den.
* [TB-137](https://kartverket.atlassian.net/browse/TB-137)
[TB-137]: https://kartverket.atlassian.net/browse/TB-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Spore requests gjennom flere komponenter i loggene

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Bygning.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Egenregistrering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Etasje.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClient.kt
- infrastructure/src/test/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClientTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BygningRouteTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/HTTP.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/bygning/BygningEksternResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregistreringRequest.kt
* Flytt metadata for listeverdier (energi og oppvarming) til å være for hele listen med verdier og ikke per felt
* Flytt metadata for bruksareal for etasjer på toppnivå
* Fiks Swagger generering til å unngå oneOf(null, type) for null-properties og bare marker de som ikke required
TB-143
> Fjern null verdier fra innsending av egenregistrering og uthenting av data

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/bygning/BygningRepository.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/bygning/BygningService.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/database/repositories/bygning/BygningRepositoryImpl.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/BygningRepositoryTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BygningRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/common/DateTime.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/common/ErrorResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/InternRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/ArkivRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningRoutes.kt
Lukket den forrige PRen pga trøbbel med force pushing etc etter at branchen den bygde på ble merget: https://github.com/kartverket/matrikkel-bygning-egenregistrering/pull/214 
Det må være mulig å hente ut tilstanden for egenregistrerte data for et gitt tidspunkt tilbake i tid. Dette er blant annet nødvendig for å støtte egenregistrert data inn i Historisk Matrikkelbrev (lovkrav).
- **To nye interne endepunkter for uthenting av egenregistrert data basert på registreringstidspunkt**, for henholdvis bygning og bruksenhet. Nytt tillegg på route oppbygningen: `/arkiv?registreringstidspunkt=<datoher>`
- **Gjenbrukt funksjonene i service laget ved å legge til et nytt parameter for registreringstidspunkt** som defaulter til `Instant.now()` - etter samtale med William. I databasen, rent teknisk, …
> TB-140 Legg til nye endepunkter for arkivarisk historikk

- .gitignore
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/bygning/BygningRepository.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/bygning/BygningService.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringService.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/hendelser/HendelseRepository.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/hendelser/HendelseService.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/hendelser/Hendelser.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/database/repositories/EgenregistreringRepositoryImpl.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/database/repositories/HendelseRepositoryImpl.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/database/repositories/bygning/BygningRepositoryImpl.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/BygningRepositoryTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/HendelseRepositoryTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/ekstern/bygning/BygningEksternTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/StatusPages.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/common/ErrorResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/EksternRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/hendelse/HendelseEksternResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/hendelse/HendelseEksternRoutes.kt
- web/src/main/resources/db/migration/V1__init_db.sql
Per nå er det kun lagring av egenregistreringer som forårsaker en hendelse, men oppsettet er generelt nok til at det skal kunne tåle flere typer hendelser fremover, som kunne vært hensiktsmessig å prøve ut.
Ting er forsøkt holdt ganske enkelt i første omgang så ting er lettere å forholde seg til. På sikt så vil det nok være ønskelig å få bedre oversikt over "hva skjedde ved x hendelse", som man ikke får i noen stor grad nå.
> Lag eget endepunkt for henting av hendelser

- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/RegistreringAktoerTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- infrastructure/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/BygningRepositoryTest.kt
- infrastructure/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/EgenregistreringRepositoryTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/TestApplicationWithDb.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/MockOAuth2ServerExtensions.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/ekstern/bygning/BygningEksternTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BygningArkivRouteTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BygningRouteTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/authentication/Authentication.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/authentication/mock/MockJWTConfig.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/RouteExtensions.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/InternRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/ArkivRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregisteringRoutes.kt
- web/src/main/resources/application-local.conf
- web/src/main/resources/application.conf
* Legger til ny auth provider som validerer issuer, audience og custom roller
* Går tilbake fra custom principal og beholder i stedet JWTPrincipal da det er mer felles for de ulike providerne.
* Skriver om mock oppsettet slik at vi setter korrekt JWTPrincipal. Har mulighet for default token, men også mulig å overstyre tokenet for de ulike providerne.
* Flyttet på arkiv-tester for å unngå for mange tester i samme fil.
TB-188
> Krev Entra JWT token med custom rolle for å hente ut arkivarisk historikk

- gradle/libs.versions.toml
- web/build.gradle.kts
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/EksternRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/berettigetinteresse/bygning/BygningBerettigetInteresseRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/hendelse/HendelseRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/MedPersondataRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/BygningMedPersondataRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/InternRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/ArkivRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BruksenhetRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregisteringRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/kodeliste/KodelisteRoutes.kt
Fjerner også pakkenavn fra typenavnene (TB-205)
Samler eksterne OpenAPI-spesifikasjoner i samme Swagger-UI nå som det er mulig
> TB-203: Oppgraderer til ktor-swagger-ui 5

- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/EksternRoutes.kt
Ser ut til å være en bug i ktor-openapi, vet ikke helt hvorfor det skjer, kanskje noe med extension funksjonen som ikke blir plukka opp.
> Fiks manglende protected block på ekstern routes

- Dockerfile
Fått ut hash fra `docker buildx imagetools inspect eclipse-temurin:21-jdk-alpine`. Kan eventuelt leses fra [Docker Hub](https://hub.docker.com/layers/library/eclipse-temurin/21-alpine/images/sha256-1b8c1c466d6a7c739cbac9c8a1bd56d5cadfeea900d65b99db6b992c3b7e19ef)
> Pin docker image til spesifikk digest

- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/BygningMedPersondataResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataResponse.kt
prosess skal oppluse egenregistrerte data i eksterne responser slik at det er lett for brukerene å vite hvilken data de konsumerer
-TB-196
> Bruk av prosesskode i eksterne responser

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Bygning.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BruksenhetRouteTest.kt
Foreslår at vi ikke legger inn noen måte å avinstallere uten å sende med opphørsår med det første. Det vil kreve en del endringer, og jeg gjetter at vi er enige at dette gir mening å legge til i første omgang uansett
> Fjern egenregistrerte verdier med opphørsår fra bruksenhetsaggregat

- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/ekstern/berettigetinteresse/bygning/BygningBerettigetInteresseTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/ekstern/medpersondata/bygning/BygningMedPersondataTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/berettigetinteresse/bygning/BygningBerettigetInteresseResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/BygningMedPersondataResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataResponse.kt
Får ikke brukt hjelpefunksjonene da etasje oppfører seg som gammel oppvarming/energikilder. Siden det bare gjelder ett felt så tenker jeg det er greit at det bare har sine egne mappingfunksjoner.
> Legg til areal per etasje i eksterne responser
