kartverket/matrikkel-bygning-egenregistrering

- src/intTest/kotlin/no/kartverket/matrikkel/bygning/v1/BygningRouteTest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/Bygning.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/BygningClient.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/LocalBygningClient.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/matrikkel/adapters/MatrikkelBygningClient.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Result.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/requests/EgenregistreringRequest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/BygningRoutes.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/EgenregisteringRoutes.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringValidationService.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringsService.kt
Lagde en PR inn i den andre branchen så det var lettere å se diff på bare endringene dine @henriwi
> Forslag til bruk av custom Result-type og flytting av logikk ned fra route til service

- .github/workflows/build-deploy.yaml
- .github/workflows/bump-dev-to-test.yaml
- .github/workflows/promote-dev-to-test.yaml
Fordrer at følgende PRer er inne:
* https://github.com/kartverket/bygning-apps/pull/9
* https://github.com/kartverket/bygning-github-workflows/pull/2
> Add dev to test promoter

- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/egenregistrering/EgenregistreringRouteTest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringService.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringValidator.kt
- src/test/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringValidatorTest.kt
* Legger til en logisk sjekk på at man ikke skal ha flere registreringer med samme bruksenhetID
* Oppretter EgenregistreringValidator for å samle valideringsfeil
* Flytter litt på test fra integrasjonstest til validator da dette sjekkes direkte av validatoren
> TB-77 Ikke tillat flere bruksenhetsregistreringer med samme id på bruksenhet

- catalog-info.yaml
Denne PRen oppdaterer `catalog-info.yaml` for å gi entiteter til Backstage.
> [Sikkerhet] Oppdaterer med catalog-info.yaml

- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/EgenregistreringRepositoryTest.kt
- src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/egenregistrering/EgenregistreringRouteTest.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Bygning.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/BygningExtensions.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/models/Egenregistrering.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/bygning/BygningResponse.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregisteringRoutes.kt
- src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregistreringRequest.kt
- src/test/kotlin/no/kartverket/matrikkel/bygning/models/BygningExtensionsTest.kt
- src/test/kotlin/no/kartverket/matrikkel/bygning/services/EgenregistreringValidatorTest.kt
Alle feltene er fortsatt også på bygningsnivå i bygningsmodellen for konvertert/utledet fra matrikkelen.
> TB-89: All egenregistrering på bruksenhetnivå

- .github/CODEOWNERS
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregisteringRoutes.kt
Kom visst med en commit jeg hadde hadde satt på feil branch, men den er så liten og søt at den kanskje kan godkjennes?
> Oppdater Security Champion

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
@espgus sin PR fikk meg til å tenke at aggregeringen kunne forbedres litt, så gjorde at man har litt mindre sjekker i noe som blir sjekket for alle individuelle felter. La til en revers av testen for bruksareal vs. total sånn at begge caser er dekket, siden de er litt annerledes :) Fikk hvert fall slettet litt kode med dette og det er jo alltids nice
Kunne også vurdert å legge til en optional condition i `aggregate()`, men vet ikke om det er nødvendig
> Forbedring av aggregering

- docs/patterns-og-arkitektur.md
Kommer ikke på noen andre ting som er verdt å nevne nå i første omgang :)
> Legg til dokumentasjon for patterns og arkitektur

- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/ByggeaarDeriver.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClient.kt
- infrastructure/src/test/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/builders/BygningsstatusHistorikkBuilder.kt
- infrastructure/src/test/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/ByggeaarDeriverTest.kt
Legg til registrert dato for statusen som ble brukt for å derivere byggeåret som regtidspunkt i RegisterMetadata, samt signatur på statusen
> Registreringsdato for derivert byggeår ved derivering av byggeår 

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Egenregistrering.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
Validering av kildemateriale på egentregisterte data i hendhold til gitt definisjon
> Validering av kildemateriale

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Egenregistrering.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregisteringRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregistreringRequest.kt
* Muligheten til å sende inn og hente ut kildemateriale for BruksarealRegistrering
* La til videre validering av kildemateriale mot BruksarealRegistrering
> Kildemateriale i BruksarealRegistrering

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Egenregistrering.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/bygning/BygningResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregisteringRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/egenregistrering/EgenregistreringRequest.kt
Endrer logikken for BRA slik at total alltid registreres, men per etasje er frivillig. Justert litt på tester for å dekke disse casene. Også lagt inn validering på at totalt må være likt summen av etasjene
> Total BRA skal alltid registreres, BRA per etasje frivillig

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/kodelister/EgenregistreringKoder.kt
Etter ønske fra Kristin i Egenreg
> Fjern salgsrapport fra beskrivelse

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Bygning.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Egenregistrering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/kodelister/EgenregistreringKoder.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/database/repositories/EgenregistreringRepositoryImpl.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/ByggeaarDeriver.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/LocalBygningClient.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClient.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/EgenregistreringRepositoryTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregistreringRequest.kt
- web/src/main/resources/application-local.conf
* Denne oppgaven ut på å legge inn støtte for prosess som metadata på registreringen. Noe som skjer i bak kulissene
* TB-113
> Registere prosess som metadata

- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/LocalBygningClient.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClient.kt
> Retter en feil hvor prosess blir registrert på bruksenhet.

- .github/workflows/build-deploy-pr.yaml
- .github/workflows/build-deploy.yaml
* dette ble lagt til så workflows kan gjenbrukes på tvers av repos
> Legger til identity-input i workflow

- web/src/main/resources/application.conf
> Fjern konfigurasjon for å disable maskinporten og bruke matrikkel stub i miljøene

- gradle/libs.versions.toml
Det er ikke så mye å se på kodemessig. Det spennende er å se om feilen er borte når man kjører applikasjonen.
> Oppgraderer schema-kenerator for å fikse feil med arvede felt

- web/src/main/kotlin/no/kartverket/matrikkel/bygning/Application.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/plugins/OpenAPI.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/EksternRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/berettigetinteresse/BerettigetInteresseRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/berettigetinteresse/bygning/BygningBerettigetInteresseResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/berettigetinteresse/bygning/BygningBerettigetInteresseRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/UtenPersondataRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataRoutes.kt
Veldig likt som #237, men legger til to nye nivåer
> Legg til eksterne routes for berettiget interesse og uten persondata

- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/BygningMedPersondataResponse.kt
- web/src/test/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/FeltMedPersondataResponseTest.kt
Endrer det bare til en String ut, slik som vi gjør internt.
> Fiks serialisering av RegistrertAv

- application/build.gradle.kts
> Legg til kompilatorflagg som fjerner warnings fra build-loggen

- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringService.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidator.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Bygning.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/BygningEgenregistreringAggregering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Egenregistrering.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/Etasje.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/ids/EgenregistreringId.kt
- application/src/main/kotlin/no/kartverket/matrikkel/bygning/application/models/kodelister/BygningKoder.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/egenregistrering/EgenregistreringValidatorTest.kt
- infrastructure/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/repositories/EgenregistreringRepositoryTest.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/database/repositories/EgenregistreringRepositoryImpl.kt
- infrastructure/src/main/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClient.kt
- infrastructure/src/test/kotlin/no/kartverket/matrikkel/bygning/infrastructure/matrikkel/client/MatrikkelBygningClientTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/common/EgenregistreringUtils.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BruksenhetRouteTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/bygning/BygningRouteTest.kt
- web/src/integrationTest/kotlin/no/kartverket/matrikkel/bygning/v1/intern/egenregistrering/EgenregistreringRouteTest.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/common/ErrorResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/berettigetinteresse/bygning/BygningBerettigetInteresseResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/BygningMedPersondataResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/utenpersondata/bygning/BygningUtenPersondataResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningInternResponse.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/bygning/BygningRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregisteringRoutes.kt
- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/intern/egenregistrering/EgenregistreringRequest.kt
Legger til gyldighetsperiode som metadata på 4 av feltene som egenregistreres.
I domenemodellen ligger perioden som en egen klasse slik at vi enklere kan gjøre validering og liknende på datoene. Har ikke tatt med sletting i første omgang siden det var litt å gå opp der på hvordan vi ønsker å lagre slette-handlingen.
Det ligger et par TODO vedrørende Gyldighet som jeg tenker er greit å høre deres meninger om, derfor de fortsatt ligger der. Legger til en kommentar på de så det er lettere å få med seg
I tillegg:
* Rydder opp litt i andre TODOs så vi har litt færre (ikke repetert der de er repetert, fjernet de vi har tatt i betraktning allerede)
* Lagd en value class for EgenregistreringId
* Renamet oppvarminger til oppvarming
> Legg til gyldighetsperiode for avløp, energikilder, oppvarming og vannforsyning

- web/src/main/kotlin/no/kartverket/matrikkel/bygning/routes/v1/ekstern/medpersondata/bygning/BygningMedPersondataResponse.kt
> Legg til gyldighetsperiode på eksternt API BygningMedPersondata

- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/BygningEgenregistreringAggregeringTest.kt
- application/src/test/kotlin/no/kartverket/matrikkel/bygning/application/ObjectMotherBuilder.kt
* hjelpeverktøy som kan lage test-objekter Slik at vi enklere kan lage tester, og terskelen for å lage flere gode tester minker
* TB-147
> Hjelpeverktøy for laging av test-objekter
